# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('provisioning', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managementnode',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ipaddress', models.CharField(db_column='IPaddress', max_length=15)),
                ('hostname', models.CharField(max_length=50)),
                ('lastcheckin', models.DateTimeField(blank=True, null=True)),
                ('checkininterval', models.IntegerField()),
                ('installpath', models.CharField(max_length=100)),
                ('imagelibenable', models.IntegerField()),
                ('imagelibuser', models.CharField(blank=True, max_length=20, null=True)),
                ('imagelibkey', models.CharField(blank=True, max_length=100, null=True)),
                ('keys', models.CharField(blank=True, max_length=1024, null=True)),
                ('sshport', models.SmallIntegerField()),
                ('publicipconfiguration', models.CharField(db_column='publicIPconfiguration', max_length=11)),
                ('publicsubnetmask', models.CharField(blank=True, db_column='publicSubnetMask', max_length=56, null=True)),
                ('publicdefaultgateway', models.CharField(blank=True, db_column='publicDefaultGateway', max_length=56, null=True)),
                ('publicdnsserver', models.CharField(blank=True, db_column='publicDNSserver', max_length=56, null=True)),
                ('sysadminemailaddress', models.CharField(blank=True, db_column='sysadminEmailAddress', max_length=128, null=True)),
                ('sharedmailbox', models.CharField(blank=True, db_column='sharedMailBox', max_length=128, null=True)),
                ('not_standalone', models.CharField(blank=True, db_column='NOT_STANDALONE', max_length=128, null=True)),
                ('availablenetworks', models.TextField()),
                ('imagelibgroupid', models.ForeignKey(blank=True, db_column='imagelibgroupid', null=True, on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resourcegroup')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
                ('stateid', models.ForeignKey(db_column='stateid', on_delete=django.db.models.deletion.CASCADE, to='core.State')),
            ],
            options={
                'db_table': 'managementnode',
            },
        ),
    ]
