# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Openstackcomputermap',
            fields=[
                ('instanceid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('computerid', models.OneToOneField(blank=True, db_column='computerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='compute.Computer')),
            ],
            options={
                'db_table': 'openstackcomputermap',
            },
        ),
        migrations.CreateModel(
            name='Openstackimagerevision',
            fields=[
                ('imagerevisionid', models.OneToOneField(db_column='imagerevisionid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image.Imagerevision')),
                ('imagedetails', models.TextField()),
                ('flavordetails', models.TextField()),
            ],
            options={
                'db_table': 'openstackimagerevision',
            },
        ),
    ]
