# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'adminlevel',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('shibname', models.CharField(blank=True, max_length=60, null=True)),
                ('dataupdatetext', models.TextField(db_column='dataUpdateText')),
                ('sitewwwaddress', models.CharField(blank=True, max_length=56, null=True)),
                ('helpaddress', models.CharField(blank=True, max_length=32, null=True)),
                ('shibonly', models.IntegerField()),
                ('theme', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'affiliation',
            },
        ),
        migrations.CreateModel(
            name='Continuations',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('expiretime', models.DateTimeField()),
                ('frommode', models.CharField(max_length=50)),
                ('tomode', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('multicall', models.IntegerField()),
                ('deletefromid', models.CharField(max_length=255)),
                ('parentid', models.ForeignKey(blank=True, db_column='parentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Continuations')),
            ],
            options={
                'db_table': 'continuations',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'documentation',
            },
        ),
        migrations.CreateModel(
            name='Imtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'IMtype',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('prettyname', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=255)),
                ('perlpackage', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Osinstalltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'OSinstalltype',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='Privnode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, to='core.Privnode')),
            ],
            options={
                'db_table': 'privnode',
            },
        ),
        migrations.CreateModel(
            name='Sitemaintenance',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('ownerid', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('usermessage', models.TextField()),
                ('informhoursahead', models.SmallIntegerField()),
                ('allowreservations', models.IntegerField()),
            ],
            options={
                'db_table': 'sitemaintenance',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('serialization', models.CharField(max_length=12)),
                ('value', models.TextField()),
                ('setby', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'variable',
            },
        ),
        migrations.AlterUniqueTogether(
            name='privnode',
            unique_together=set([('parent', 'name')]),
        ),
    ]
