# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provisioning',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('prettyname', models.CharField(max_length=70)),
                ('moduleid', models.ForeignKey(db_column='moduleid', on_delete=django.db.models.deletion.CASCADE, to='core.Module')),
            ],
            options={
                'db_table': 'provisioning',
            },
        ),
        migrations.CreateModel(
            name='Provisioningosinstalltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osinstalltypeid', models.ForeignKey(db_column='OSinstalltypeid', on_delete=django.db.models.deletion.CASCADE, to='core.Osinstalltype')),
                ('provisioningid', models.ForeignKey(db_column='provisioningid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Provisioning')),
            ],
            options={
                'db_table': 'provisioningOSinstalltype',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.IntegerField()),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Resourcegroup',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ownerusergroupid', models.ForeignKey(db_column='ownerusergroupid', on_delete=django.db.models.deletion.CASCADE, to='authentication.Usergroup')),
            ],
            options={
                'db_table': 'resourcegroup',
            },
        ),
        migrations.CreateModel(
            name='Resourcegroupmembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcegroupid', models.ForeignKey(db_column='resourcegroupid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resourcegroup')),
                ('resourceid', models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resource')),
            ],
            options={
                'db_table': 'resourcegroupmembers',
            },
        ),
        migrations.CreateModel(
            name='Resourcemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcegroupid1', models.ForeignKey(db_column='resourcegroupid1', on_delete=django.db.models.deletion.CASCADE, related_name='R1', to='provisioning.Resourcegroup')),
                ('resourcegroupid2', models.ForeignKey(db_column='resourcegroupid2', on_delete=django.db.models.deletion.CASCADE, related_name='R3', to='provisioning.Resourcegroup')),
            ],
            options={
                'db_table': 'resourcemap',
            },
        ),
        migrations.CreateModel(
            name='Resourcepriv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=13)),
                ('privnodeid', models.ForeignKey(db_column='privnodeid', on_delete=django.db.models.deletion.CASCADE, to='core.Privnode')),
                ('resourcegroupid', models.ForeignKey(db_column='resourcegroupid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resourcegroup')),
            ],
            options={
                'db_table': 'resourcepriv',
            },
        ),
        migrations.CreateModel(
            name='Resourcetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'resourcetype',
            },
        ),
        migrations.CreateModel(
            name='Statgraphcache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphtype', models.CharField(max_length=11)),
                ('statdate', models.DateField()),
                ('value', models.IntegerField()),
                ('affiliationid', models.ForeignKey(blank=True, db_column='affiliationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Affiliation')),
                ('provisioningid', models.ForeignKey(blank=True, db_column='provisioningid', null=True, on_delete=django.db.models.deletion.CASCADE, to='provisioning.Provisioning')),
            ],
            options={
                'db_table': 'statgraphcache',
            },
        ),
        migrations.AddField(
            model_name='resourcemap',
            name='resourcetypeid1',
            field=models.ForeignKey(db_column='resourcetypeid1', on_delete=django.db.models.deletion.CASCADE, related_name='R2', to='provisioning.Resourcetype'),
        ),
        migrations.AddField(
            model_name='resourcemap',
            name='resourcetypeid2',
            field=models.ForeignKey(db_column='resourcetypeid2', on_delete=django.db.models.deletion.CASCADE, related_name='R4', to='provisioning.Resourcetype'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='resourcetypeid',
            field=models.ForeignKey(db_column='resourcetypeid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resourcetype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resourcetypeid',
            field=models.ForeignKey(db_column='resourcetypeid', on_delete=django.db.models.deletion.CASCADE, to='provisioning.Resourcetype'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepriv',
            unique_together=set([('resourcegroupid', 'privnodeid', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcemap',
            unique_together=set([('resourcegroupid1', 'resourcegroupid2')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroupmembers',
            unique_together=set([('resourceid', 'resourcegroupid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroup',
            unique_together=set([('resourcetypeid', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('resourcetypeid', 'subid')]),
        ),
        migrations.AlterUniqueTogether(
            name='provisioningosinstalltype',
            unique_together=set([('provisioningid', 'osinstalltypeid')]),
        ),
    ]
